import sys
from pathlib import Path
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon
from src.components.Logo.logo import Logo
from src.components.BrowseElement.browse_element import BrowseElement
from src.components.MessageBox.message_box import MessageBox
from src.components.HorizontalSeparator.horizontal_separator import HorizontalSeparator
from src.components.ConvertButton.convert_button import ConvertButton
from src.components.MenuBar.menu_bar import MenuBar
from src.components.StatusBar.status_bar import StatusBar
from src.components.ProgressBar.progress_bar import ProgressBar


class Ui_MainWindow(object):
    """Main UI class. The bare bone of this class was generated by QtDesigner."""

    def setupUi(self, MainWindow: QtWidgets.QMainWindow) -> None:
        """Function for setting up all the elements of the UI. This method was generated by QtDesigner and then populated.

        Args:
            MainWindow (QtWidgets.QMainWindow): MainWindow object.
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(300, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(400, 390, 120, 80))
        self.widget.setObjectName("widget")

        MainWindow.setWindowTitle("TDMS Converter")

        MainWindow.setWindowIcon(
            QIcon(f'{Path(__file__).parent / "src" / "assets" / "python_logo.svg"}')
        )

        MainWindow.setStyleSheet(
            open(
                Path(__file__).parent
                / "src"
                / "components"
                / "MainWindow"
                / "styles"
                / "classic-style.css"
            ).read()
        )

        self.tdms_logo = (
            Logo("", self.centralwidget)
            .set_name("tdms_logo")
            .set_size((120, 60))
            .set_image("tdms-logo.svg")
        )

        self.separator_line_1 = (
            HorizontalSeparator(self.centralwidget)
            .set_name("seperator_line_1")
            .set_size((272, 1))
        )
        self.message_box = (
            MessageBox(self.centralwidget)
            .set_name("message_box")
            .set_size((270, 60))
            .set_text("")
        )
        self.separator_line_2 = (
            HorizontalSeparator(self.centralwidget)
            .set_name("seperator_line_2")
            .set_size((272, 1))
        )

        self.browse_source_element = (
            BrowseElement(self.centralwidget)
            .set_size((290, 40))
            .set_name("source_browser")
            .set_textbox_text("Path to TDMS file")
        )

        self.browse_destination_element = (
            BrowseElement(self.centralwidget)
            .set_size((290, 40))
            .set_name("destination_browser")
            .set_textbox_text("Path to destination file")
        )

        self.separator_line_4 = (
            HorizontalSeparator(self.centralwidget)
            .set_name("seperator_line_3")
            .set_size((272, 1))
        )

        self.separator_line_5 = (
            HorizontalSeparator(self.centralwidget)
            .set_name("seperator_line_5")
            .set_size((272, 1))
        )

        self.progress_bar = (
            ProgressBar(self.centralwidget).set_name("progress_bar").set_size((270, 30))
        )

        self.status_bar = StatusBar(MainWindow).set_name("status_bar")

        self.convert_button = (
            ConvertButton("Convert", self.centralwidget)
            .set_name("converter_button")
            .set_size((121, 40))
            .pass_down_widget(
                self.browse_source_element,
                self.browse_destination_element,
                self.message_box,
                self.progress_bar,
                self.status_bar,
            )
        )

        layout = QtWidgets.QGridLayout()
        layout.addWidget(self.tdms_logo, 0, 0, alignment=QtCore.Qt.AlignCenter)
        layout.addWidget(self.separator_line_1, 1, 0, alignment=QtCore.Qt.AlignCenter)
        layout.addWidget(self.message_box, 2, 0, alignment=QtCore.Qt.AlignCenter)
        layout.addWidget(self.separator_line_2, 3, 0, alignment=QtCore.Qt.AlignCenter)
        layout.addWidget(
            self.browse_source_element, 4, 0, alignment=QtCore.Qt.AlignCenter
        )
        layout.addWidget(
            self.browse_destination_element, 5, 0, alignment=QtCore.Qt.AlignCenter
        )
        layout.addWidget(self.separator_line_4, 6, 0, alignment=QtCore.Qt.AlignCenter)
        layout.addWidget(self.convert_button, 7, 0, alignment=QtCore.Qt.AlignCenter)
        layout.addWidget(self.separator_line_5, 8, 0, alignment=QtCore.Qt.AlignCenter)
        layout.addWidget(self.progress_bar, 9, 0, alignment=QtCore.Qt.AlignCenter)

        layout.setHorizontalSpacing(0)
        layout.setVerticalSpacing(0)
        self.centralwidget.setLayout(layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menu_bar = (
            MenuBar(MainWindow)
            .set_name("menu_bar")
            .set_geometry((0, 0, 300, 20))
            .pass_down_widget(self.tdms_logo, self.message_box)
        )

        MainWindow.setMenuBar(self.menu_bar)
        MainWindow.setStatusBar(self.status_bar)


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
